### ISSUE TITLE
Can't install the shard with crystal v0.34.0

### ISSUE THREAD

**Issue by renich** [jhass/crystal-gobject#45]
I get the following:

```
$ shards install
Resolving dependencies
Fetching https://github.com/jhass/crystal-gobject.git
Installing gobject (0.3.0 at 09f02b85e533e6cdb74a96c78ef76727fac53b56)
Unhandled exception: Error creating symlink: '../../lib' -> '/home/renich/test/lib/gobject/lib': File exists (File::AlreadyExistsError)
  from Crystal::System::File::symlink<String, String>:Int32
  from File::symlink<String, String>:Int32
  from Shards::Package#install:(Int32 | Nil)
  from Shards::Commands::Install#install<Shards::Package>:(Shards::Package | Nil)
  from Shards::Commands::Install#install<Array(Shards::Package)>:Nil
  from Shards::Commands::Install#run:Nil
  from Shards::Commands::Install
  from ~procProc(Array(String), Array(String), Nil)
  from OptionParser::ParseTask#parse:Nil
  from OptionParser#parse<Array(String)>:Nil
  from Shards::run:OptionParser
  from __crystal_main
  from Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil
  from Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32
  from main
  from __libc_start_main
  from _start
  from ???
```

**Comment by jhass** [comment]
Ups, try 0.3.1 :)

**Comment by renich** [comment]
Works!

Just an observation. The README says:

```
dependencies:
  gobject:
    github: jhass/crystal-gobject
    branch: 0.3.1
```

And it should be:

```
dependencies:
  gobject:
    github: jhass/crystal-gobject
    branch: v0.3.1
```
