### ISSUE TITLE
Error: no overload matches 'Gtk::Builder#connect_signals' with type Nil

### ISSUE THREAD

**Issue by gummybears** [jhass/crystal-gobject#71]
Hi,

When I use version 0.8.0 I am getting the following error
```
Showing last frame. Use --error-trace for full trace.

In lib/gobject/src/gtk/gtk.cr:18:7

 18 | connect_signals nil
      ^--------------
Error: no overload matches 'Gtk::Builder#connect_signals' with type Nil

Overloads are:
 - Gtk::Builder#connect_signals(user_data : ::Pointer(Void))
 - Gtk::Builder#connect_signals()
```
This error does not occur when I use branch v0.3.1
```
dependencies:
  gobject:
    github: jhass/crystal-gobject
    branch: v0.3.1
```
